name: Windows - Litemanager
on:
  workflow_dispatch:  # Correct event trigger for a manual workflow

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    
    steps:
      - name: Downloading & installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://github.com/chamodf12/m_win-10_github_rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat
      - name: Connect to Litemanager
        run: cmd /c show bat
      - name: Time Counter
        run: cmd /c loop bat
